name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  ruby_version: 3.3

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2, 3.3, jruby-9.4]
        actionmailer: [7.1, 7.2, '8.0', main]

        exclude:
          # ActionMailer 7.2 is Ruby >= 3.1
          - actionmailer: 7.2
            ruby: 2.7
          - actionmailer: 7.2
            ruby: 3.0
          # ActionMailer 8.0 is Ruby >= 3.2
          - actionmailer: '8.0'
            ruby: 2.7
          - actionmailer: '8.0'
            ruby: 3.0
          - actionmailer: '8.0'
            ruby: 3.1
          - actionmailer: '8.0'
            ruby: jruby-9.4
          # ActionMailer main is Ruby >= 3.2
          - actionmailer: main
            ruby: 2.7
          - actionmailer: main
            ruby: 3.0
          - actionmailer: main
            ruby: 3.1
          - actionmailer: main
            ruby: jruby-9.4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install gems
        run: bundle install
        env:
          BUNDLE_GEMFILE: gemfiles/actionmailer-${{ matrix.actionmailer }}.gemfile

      - name: Test
        run: bundle exec rake spec
        env:
          BUNDLE_GEMFILE: gemfiles/actionmailer-${{ matrix.actionmailer }}.gemfile

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'development'
          bundle install

      - name: Rubocop
        run: bundle exec rake rubocop
